import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import Storeprovider from "./Storeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Storeprovider>{children}</Storeprovider>
      </body>
    </html>
  );
}
