export const CapsRatingSidebar = [
  {
    id: 1,
    name: "Financial Analysis",
    link: "/admin/caps/balancesheet",
    slug: "balancesheet",
    status: false,
  },
  {
    id: 2,
    name: "Rating Data",
    link: "/admin/caps/rating",
    slug: "rating",
    status: false,
  },
  {
    id: 3,
    name: "Photo Upload",
    link: "/admin/caps/media",
    slug: "media",
    status: false,
  },
  {
    id: 4,
    name: "Proposal",
    link: "/admin/caps/proposal",
    slug: "proposal",
    status: false,
  },
  {
    id: 5,
    name: "Credit Rating Report",
    link: "/admin/caps/report",
    slug: "report",
    status: false,
  },
  {
    id: 6,
    name: "Back to Home",
    link: "/admin/caps/products",
    slug: "caps",
    status: false,
    icon: true,
  },
];
